name: rspec

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

env:
  RACK_ENV: test
  POSTGRES_USERNAME: sequent
  POSTGRES_PASSWORD: sequent
  POSTGRES_DB: sequent_spec_db

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:

          - ruby-version: 3.0.0
            active-star-version: '< 6.1.5'
          - ruby-version: 3.0.0
            active-star-version: '6.1.4.1'
          - ruby-version: 3.0.0
            active-star-version: '< 6.0.4'
          - ruby-version: 2.7
            active-star-version: '< 6.0.3'

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: sequent
          POSTGRES_PASSWORD: sequent
          POSTGRES_DB: sequent_spec_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: false
      - name: Setup database
        run: |
          bundle exec rake db:create
      - name: Run tests
        run: bundle exec rspec
